"""create user weight category and parcel tables

Revision ID: 9ccca2f19653
Revises: 
Create Date: 2026-08-25 13:04:07.144416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ccca2f19653'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weight_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weight_category_id', sa.UUID(), nullable=False),
    sa.Column('pickup_address', sa.String(length=255), nullable=False),
    sa.Column('pickup_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('pickup_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('destination_address', sa.String(length=255), nullable=False),
    sa.Column('destination_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('destination_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('present_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('present_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weight_category_id'], ['weight_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcels')
    op.drop_table('weight_categories')
    op.drop_table('users')
    # ### end Alembic commands ###
